---
name: Checks

on: [push]

jobs:
  test-lint:
     name: Test & Lint
     runs-on: ubuntu-20.04
     steps:
      - name: login to Docker hub
        users: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKER_HUB_USER}}
           password: ${{ secrets.DOCKER_HUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run:  docker-compose run --rm app sh -c "python manage.py test" 
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      
